name: jmas_asistencias
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  http: ^1.2.2 #WEB
  shared_preferences: ^2.3.3 #Guardar token
  intl: ^0.19.0 #Fecha
  image_picker: ^1.1.2 #Seleccionar imagen
  path_provider: ^2.1.5 #Provider
  connectivity_plus: ^6.1.4 #Conexión
  google_mlkit_face_detection: ^0.13.1 
  google_mlkit_barcode_scanning: ^0.14.1
  camera: ^0.11.2
  path: ^1.9.1
  image: ^4.5.4
  local_auth: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
      - assets/gifs/
      - assets/png/